/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Government;

import Business.Appointment.Appointment;
import Business.Disease;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.GovernmentEnterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Network.Network;
import Business.Organization.ConsumerOrganization;
import Business.Organization.Organization;
import Business.Person.Consumer;
import Business.Person.Person;
import Business.UserAccount.UserAccount;
import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import javax.swing.JPanel;
import jdk.nashorn.internal.runtime.arrays.ArrayLikeIterator;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Rupam Tiwari
 */
public class ManageEmbassyWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form ManageEmbassyWorkArea
     */
    
    JPanel sequencer;
    Network network;
    GovernmentEnterprise enterprise;
    private Organization organization;
    UserAccount userAccount;
    EcoSystem system;
    

    public ManageEmbassyWorkArea(JPanel sequencer, Network network, Enterprise enterprise, Organization organization, UserAccount userAccount, EcoSystem system) {
        initComponents();
        this.sequencer = sequencer;
        this.network = network;
        this.enterprise = (GovernmentEnterprise)enterprise;
        this.organization = organization;
        this.userAccount = userAccount;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnPieChart = new javax.swing.JButton();
        ChartLayredPane = new javax.swing.JLayeredPane();

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Embassy Work Area");

        btnPieChart.setText("PieChart");
        btnPieChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPieChartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ChartLayredPaneLayout = new javax.swing.GroupLayout(ChartLayredPane);
        ChartLayredPane.setLayout(ChartLayredPaneLayout);
        ChartLayredPaneLayout.setHorizontalGroup(
            ChartLayredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 629, Short.MAX_VALUE)
        );
        ChartLayredPaneLayout.setVerticalGroup(
            ChartLayredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPieChart)
                            .addComponent(ChartLayredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(308, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(btnPieChart)
                .addGap(18, 18, 18)
                .addComponent(ChartLayredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPieChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPieChartActionPerformed
        // TODO add your handling code here:
        DefaultPieDataset pieDataset = new DefaultPieDataset();
        
         //Consumer c= (Consumer)userAccount.getPerson();
         ConsumerOrganization corg=system.getConsumerOrgInstance();
         ArrayList<Consumer> tempArray;
         Map<String,Integer> diseaseHM = new HashMap();
         
         tempArray = corg.getConsumerByCountry(organization.getName()) ;
         for(Disease dis: system.getDiseaseCatalog()){
             diseaseHM.put(dis.getName(), 0);
         for(Consumer cons : tempArray){if(cons.getAppDir().searchDisease(dis))
                 {
                     diseaseHM.put(dis.getName(), diseaseHM.get(dis.getName())+1);
                 }}}
        
        Iterator it = diseaseHM.entrySet().iterator();
        while (it.hasNext()) {
        Map.Entry pair = (Map.Entry)it.next();
        pieDataset.setValue((String)pair.getKey(),(Integer)pair.getValue());
        it.remove();
        }
        
        
        JFreeChart chart = ChartFactory.createPieChart("PieChart", pieDataset, true, true,true);
        PiePlot P = (PiePlot)chart.getPlot();
       // P.setForegroundAlpha(TOP_ALIGNMENT);
        ChartPanel frame = new ChartPanel(chart);
        ChartLayredPane.add(frame);
        frame.setVisible(true);
        frame.setSize(400,500);
                       
    }//GEN-LAST:event_btnPieChartActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane ChartLayredPane;
    private javax.swing.JButton btnPieChart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
