/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Enterprise;

import Business.EcoSystem;
import Business.Enterprise.ConsumerEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.GovernmentEnterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.Organization.OrganizationType;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rupam Tiwari
 */
public class ManageOrganization extends javax.swing.JPanel {

    /**
     * Creates new form ManageOrganization
     */
    JPanel sequencer;
    Network network;
    Enterprise enterprise;
    private Organization organization;
    UserAccount userAccount;
    EcoSystem system;
    
    public ManageOrganization(JPanel sequencer, Network network, Enterprise enterprise, Organization organization, UserAccount userAccount, EcoSystem system) {
        initComponents();
        this.sequencer = sequencer;
        this.network = network;
        this.enterprise = enterprise;
        this.organization = organization;
        this.userAccount = userAccount;
        this.system = system;
        
       populateorganizationTypeCombo();
       populateTable();
    }
    
    public void populateorganizationTypeCombo(){
        
        for (Organization.OrganizationType type : Organization.OrganizationType.values()) {

           if (!type.getValue().equals(userAccount.getRole())){//Type.Admin.getValue())) {

            if (enterprise instanceof HospitalEnterprise) {
                if (type.getValue().equals(type.TPHospitalAppintmentScheduler.getValue())) {
                        comboOrganizationType.addItem(type);

                } else if (type.getValue().equals(type.TPHospitalOperation.getValue())) {
                        comboOrganizationType.addItem(type);
            }}
            if (enterprise instanceof GovernmentEnterprise) {
                if (type.getValue().equals(type.GovernmentOrganization.getValue())) {
                        comboOrganizationType.addItem(type);

                   }else if (type.getValue().equals(type.EmbassyOrganization.getValue())) {
                        comboOrganizationType.addItem(type);
            }}
            if (enterprise instanceof ConsumerEnterprise) {
                if (type.getValue().equals(type.ConsumerOrganization.getValue())) {
                        comboOrganizationType.addItem(type);
                   }}

}
}
        
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) tableOrganization.getModel();
        model.setRowCount(0);
        
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            Object[] row = new Object[2];
            row[0] = organization;
            row[1] = organization.getType().getValue();
            
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableOrganization = new javax.swing.JTable();
        btnAddOrganization = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        textOrganizationName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboOrganizationType = new javax.swing.JComboBox();
        btnSave = new javax.swing.JButton();
        btnRemoveOrganization = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jLabel1.setText("Manage Organization");

        tableOrganization.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Organization Name", "Organization Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableOrganization);

        btnAddOrganization.setText("Add Organization");
        btnAddOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOrganizationActionPerformed(evt);
            }
        });

        jLabel2.setText("Organization Name");

        textOrganizationName.setEnabled(false);

        jLabel3.setText("Organization Type");

        comboOrganizationType.setEnabled(false);

        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnRemoveOrganization.setText("Remove Organization");
        btnRemoveOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveOrganizationActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(305, 305, 305)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSave)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textOrganizationName)
                                    .addComponent(comboOrganizationType, 0, 196, Short.MAX_VALUE)))
                            .addComponent(btnAddOrganization))
                        .addGap(114, 114, 114)
                        .addComponent(btnRemoveOrganization)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnBack))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddOrganization)
                    .addComponent(btnRemoveOrganization))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textOrganizationName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboOrganizationType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOrganizationActionPerformed
        // TODO add your handling code here:
        textOrganizationName.setEnabled(true);
        comboOrganizationType.setEnabled(true);
        btnSave.setEnabled(true);
    }//GEN-LAST:event_btnAddOrganizationActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        String orgName = textOrganizationName.getText();
        OrganizationType orgType = (OrganizationType) comboOrganizationType.getSelectedItem();
        
        if(orgName.trim().equals("")){
            JOptionPane.showMessageDialog(null, "Enter some valid name!");
            return;
        }
        for(Organization org:enterprise.getOrganizationDirectory().getOrganizationList()){
            if(org.getType()==orgType && orgType!=Organization.OrganizationType.EmbassyOrganization){
               JOptionPane.showMessageDialog(null,orgType.getValue()+ " type of Organization already exist in "+enterprise.getName()+ " enterprise", "ErrorMessage",JOptionPane.ERROR_MESSAGE);
               return; 
            }
        }
        //String networkName = networkNameJTextField.getText();
            Organization organization = enterprise.getOrganizationDirectory().createAndAddOrganization(orgType, orgName, enterprise, network, system);
            if(organization!=null){
            JOptionPane.showMessageDialog(null, "Organization added!");
            }else{
                JOptionPane.showMessageDialog(null, "Organization already exist");
            }
            
            populateTable();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnRemoveOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveOrganizationActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableOrganization.getSelectedRow();
      if(selectedRow >= 0)
        {
         Organization o = (Organization)tableOrganization.getValueAt(selectedRow, 0);
         enterprise.getOrganizationDirectory().removeOrganization(String.valueOf(o));
         JOptionPane.showMessageDialog(null,"Organization Deleated Successfully");
        }else
            JOptionPane.showMessageDialog(null, "Please Select An User");
      populateTable();
        
    }//GEN-LAST:event_btnRemoveOrganizationActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        sequencer.remove(this);
        CardLayout layout = (CardLayout) sequencer.getLayout();
        layout.previous(sequencer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddOrganization;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRemoveOrganization;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox comboOrganizationType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableOrganization;
    private javax.swing.JTextField textOrganizationName;
    // End of variables declaration//GEN-END:variables
}
